#!/usr/bin/env node
/**
 * Open Bioware — static site generator.
 *
 *   node build.mjs
 *
 * Reads data/*.json, writes plain HTML to the repository root so that GitHub
 * Pages can serve it directly from the default branch with no build step.
 * No dependencies: standard library only.
 */

import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  renderHome,
  renderApp,
  renderAppsIndex,
  renderDirectory,
  renderAbout,
  render404,
  downloadUrl,
  ACCENTS,
} from "./src/render.mjs";

const root = dirname(fileURLToPath(import.meta.url));
const readJson = async (p) => JSON.parse(await readFile(join(root, p), "utf8"));

/** Pages generated by this script; removed before each build so renames cannot
 *  leave orphaned files behind. Source directories are never touched. */
const GENERATED = ["index.html", "404.html", "sitemap.xml", "robots.txt", "apps", "software", "about"];

const write = async (relPath, contents) => {
  const target = join(root, relPath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents, "utf8");
  return relPath;
};

/* --- validation --------------------------------------------------------- */

function validate(apps, directory) {
  const problems = [];
  const seen = new Set();

  for (const app of apps) {
    const where = `apps.json → ${app.slug || app.name || "<unnamed>"}`;
    for (const field of ["slug", "name", "tagline", "category", "license", "platforms"]) {
      if (!app[field] || (Array.isArray(app[field]) && !app[field].length)) {
        problems.push(`${where}: missing "${field}"`);
      }
    }
    if (seen.has(app.slug)) problems.push(`${where}: duplicate slug`);
    seen.add(app.slug);

    // apps/index.html is the catalogue page, so no app may claim that slug.
    if (app.slug === "index") {
      problems.push(`${where}: "index" is reserved for the app catalogue page`);
    }

    const type = app.download?.type ?? "github";
    if (type === "github" && !app.repo) {
      problems.push(`${where}: download.type is "github" but no "repo" is set`);
    }
    if (type === "official" && !app.download?.url) {
      problems.push(`${where}: download.type is "official" but no "download.url" is set`);
    }
    if (app.repo && !/^[\w.-]+\/[\w.-]+$/.test(app.repo)) {
      problems.push(`${where}: "repo" should be in owner/name form, got "${app.repo}"`);
    }
    // requirements may be a plain array (legacy) or { os, hardware } maps.
    const req = app.requirements;
    if (req && !Array.isArray(req)) {
      if (typeof req !== "object") {
        problems.push(`${where}: "requirements" must be an array or an object`);
      } else {
        for (const key of Object.keys(req)) {
          if (key !== "os" && key !== "hardware") {
            problems.push(`${where}: unknown requirements group "${key}" — use "os" or "hardware"`);
          } else if (typeof req[key] !== "object" || Array.isArray(req[key])) {
            problems.push(`${where}: requirements.${key} must be an object of label → value`);
          }
        }
      }
    }
    if (app.accent && !ACCENTS.includes(app.accent)) {
      problems.push(
        `${where}: unknown accent "${app.accent}" — pick one of ${ACCENTS.join(", ")}`
      );
    }
  }

  for (const group of directory) {
    for (const item of group.items) {
      const where = `directory.json → ${group.category} → ${item.name || "<unnamed>"}`;
      for (const field of ["name", "blurb", "license"]) {
        if (!item[field]) problems.push(`${where}: missing "${field}"`);
      }
      // Directory entries link out only — a website or a source repository,
      // never a download. At least one of the two must be present.
      if (!item.site && !item.repo) {
        problems.push(`${where}: needs a "site" or a "repo" to link to`);
      }
      if (item.site && !/^https?:\/\//.test(item.site)) {
        problems.push(`${where}: "site" must be an absolute URL`);
      }
    }
  }

  return problems;
}

/* --- build -------------------------------------------------------------- */

async function main() {
  const [site, apps, directory, content] = await Promise.all([
    readJson("data/site.json"),
    readJson("data/apps.json"),
    readJson("data/directory.json"),
    readJson("data/content.json"),
  ]);

  // Page prose lives in data/content.json; templates read it from here so the
  // render functions need no extra parameter threaded through every call.
  site.content = content;

  // Content-hash the stylesheet and script so a deploy cannot leave visitors
  // on a cached copy of either. Unchanged files keep their hash, and stay
  // cached; changed ones get a new URL and are fetched immediately.
  const hashOf = async (relPath) =>
    createHash("sha256").update(await readFile(join(root, relPath))).digest("hex").slice(0, 10);

  site.assets = {
    css: await hashOf("assets/css/site.css"),
    js: await hashOf("assets/js/site.js"),
  };

  const problems = validate(apps, directory);
  if (problems.length) {
    console.error("Build failed — invalid data:\n");
    for (const p of problems) console.error(`  • ${p}`);
    process.exitCode = 1;
    return;
  }

  for (const path of GENERATED) {
    const target = join(root, path);
    if (existsSync(target)) await rm(target, { recursive: true, force: true });
  }

  const written = [];
  written.push(await write("index.html", renderHome(site, apps, directory)));
  written.push(await write("apps/index.html", renderAppsIndex(site, apps, directory)));
  written.push(await write("software/index.html", renderDirectory(site, directory, apps)));
  written.push(await write("about/index.html", renderAbout(site, apps, directory)));
  written.push(await write("404.html", render404(site, apps, directory)));

  for (const app of apps) {
    written.push(await write(`apps/${app.slug}/index.html`, renderApp(site, app, apps)));
  }

  // sitemap + robots
  const routes = ["/", "/apps/", "/software/", "/about/", ...apps.map((a) => `/apps/${a.slug}/`)];
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (r) =>
      `  <url><loc>${site.url}${r}</loc><changefreq>${r === "/" ? "weekly" : "monthly"}</changefreq><priority>${r === "/" ? "1.0" : "0.7"}</priority></url>`
  )
  .join("\n")}
</urlset>
`;
  written.push(await write("sitemap.xml", sitemap));
  written.push(
    await write("robots.txt", `User-agent: *\nAllow: /\n\nSitemap: ${site.url}/sitemap.xml\n`)
  );

  // `.nojekyll` stops GitHub Pages running the files through Jekyll.
  written.push(await write(".nojekyll", ""));

  const dirCount = directory.reduce((n, g) => n + g.items.length, 0);
  console.log(`Built ${written.length} files.`);
  console.log(`  ${apps.length} app page(s), ${dirCount} directory entries in ${directory.length} categories.`);

  const placeholders = apps.filter((a) => a.placeholder);
  if (placeholders.length) {
    const n = placeholders.length;
    console.log(
      `\n  Note: ${n} placeholder app ${n === 1 ? "entry is" : "entries are"} still in ` +
        `data/apps.json (${placeholders.map((a) => a.slug).join(", ")}). ` +
        `Replace ${n === 1 ? "it" : "them"} with your own apps.`
    );
  }

  console.log(`\n  Asset versions: css ${site.assets.css} · js ${site.assets.js}`);
  console.log(`\n  Primary download targets:`);
  for (const app of apps) console.log(`    ${app.name} → ${downloadUrl(app)}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
